name: apma_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Network
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.4.11
  
  # UI
  flutter_svg: ^2.0.9
  
  # Utils
  dartz: ^0.10.1
  intl: ^0.19.0

  # XML/SOAP Support
  xml: ^6.3.0
  # grid & sort
  pluto_grid: ^8.0.0
  # convert date
  shamsi_date: ^1.1.0
  persian_datetime_picker: ^3.2.0

  # RUN IN BACKGROUND
  workmanager: ^0.9.0+3
  flutter_foreground_task: ^9.1.0

  # printing
  pdf: ^3.10.6
  printing: ^5.10.4
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  
  # ocr platform
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  geolocator: ^12.0.0
  cupertino_icons: ^1.0.8
  image: ^4.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Bold.ttf
        - asset: assets/fonts/Vazir-regular.ttf
          weight: 700

# تنظیمات آیکن اپلیکیشن
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
